name: app_name
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  initializer:
    path: initializer
  data:
    path: data
  shared:
    path: shared
  resources:
    path: resources
  domain:
    path: domain

  mini_app:
    path: mini_app

  get_it: ^7.6.7
  injectable: ^2.3.3
  iconsax: ^0.0.8
  rxdart: ^0.27.7
  provider: ^6.1.2
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lottie/
